### ISSUE TITLE
Add FOSSology to the crawler

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#100]
**See PR #103**

Running FOSSology in the crawler should be very much like running ScanCode. See `providers/process/scancode.js`. 

* the provider gets called with a some information including a directory where the content is. 
* The provider then runs FOSSology on the directory and collects the output (either piped to a file or capturing the console log or ...)
* The output is then structured as a "document" with a bit of metadata and returned.

Key points:
* The tool output (FOSSology) must be retained exactly as it was captured. It is important that future readers be able to see, read, load, and compare the actual tool output.
* The output as returned should be a JavaScript object. Ideally the FOSSology output is in JSON format. If not, we can Base64 encode the output and put it in the JavaScript "document".
* We also need to package up FOSSology and its runtime in a Docker container that can be layered into the ultimate Crawler image.
* The Crawler's visitor map also needs to be updated to run the FOSSology tool. @jeffmcaffer can help with that.

Note that the ScanCode provider has some extra function related to VSTS Build. That can be ignored. It is no longer used and likely should be removed.

**Comment by larainema** [comment]
I will separate the issue into following tasks:
1. Investigate how to run FOSSology from command line and how to collect the output?
2. Package the FOSSology tool into the Docker container
3. Run the FOSSology scan from the Docker container and store the output result.

**Comment by larainema** [comment]
Hi Jeff,

For the how to run FOSSology and collect the result, after my investigation, I have following two solutions, please help review which is more better for our project:

1. I didn't find FOSSology have a common command line to run the scan, all the license/copyright scan only have the separate agent command line, for example, FOSSology have agents like nomos, monk, ninka, copyright, pkgagent ... to run license, copyright, package scan for files. 
So one solution is to run these agents separately and get the output for each agent.

2. To handle the target files as a upload, run FOSSology scan from the FOSSology scheduler, query the scan results from FOSSology database after FOSSology scheduler scan finished.

I prefer the first solution, I can do it from one agent(nomos) as a example. What about your thought?

**Comment by jeffmcaffer** [comment]
NOT the second one. We do not want to setup and maintain a different service and then try to interact with that. 

Given that strategy, we can either
* write one `Processor` that spawns all the different FOSSology tools and combines their results into one document.
* write a different `Processor` for each FOSSology tool and have the results stored and summarized separately.

I don't know enough about how FOSSology is evolving to guide that decision. For example, 
* do all the tools get rev'd at the same time or as they all evolving independently? 
* Is the FOSSology team interested in creating a unified toolset or is the philosophy that they be, and be seen to be separate.
* Do FOSSology users know/care about the differences between the tools (e.g., is being able to get one output without the others important)?

On a related note, I sketched out how one would plug in a new tool in this branch. You might want to start with that. https://github.com/clearlydefined/crawler/tree/jm/fossologySkeleton.

For right now perhaps just go ahead and get one of the tools running (e.g., nomos) and we can get more info and pick between the approaches.

**Comment by larainema** [comment]
From my understanding, FOSSology's philosophy is trade all the tools as independently agents, users can select which agents they want to run and the output should be stored after each agent running.

Thanks for the branch, I will start with one tools running.

**Comment by daniellandau** [comment]
I have done something quite similar, i.e. running the command line tools separately and collecting their output as JSON. The code is available at https://github.com/codescoopltd/fossy-api

**Comment by jeffmcaffer** [comment]
On investigation and talking to @mcjaeger, Nomos has an SA (standalone) mode that it can be built with. That should work. The conversation implied that both monk and copyright also could run standalone but looking at the code, they both open and seem to depend on database managers unconditionally. @mcjaeger, can you comment on how to get monk and copyright to run without a database?

**Comment by craigez** [comment]
@jesseporter @michellesenar

**Comment by jeffmcaffer** [comment]
@daniellandau thanks for the pointer. Looking at that code it appears that, for example, the copyright agent still uses the database. Did you make any changes to make the agents themselves run standalone?

**Comment by daniellandau** [comment]
I wrote the JSON outputting, but left the database as is. Felt it was the path of least resistance to just let the database be, as it's anyways contained in a black box in our use case.

**Comment by mcjaeger** [comment]
We wondered in our team what would be the json format that you expect from a scanner or that you currently use, would you have an example output?

**Comment by jeffmcaffer** [comment]
Hey @mcjaeger. we are not too fussed about the format. Every tool is different so we write adapters that know about each format and convert to the structure that ClearlyDefine needs. The key thing is that whatever the tools output is machine readable. Ideally JSON but that is not essential. For example, the current Nomos console output is human readable but it is regular so we can parse it. The JSON output is insufficient as it does not have the path name of the file scanned so we have to coordinate the inputs and the outputs (possible but not natural).

The bigger problem we have right now is running the agents without a database. Completely standalone. Ideally they would output the above mentioned machine readable form that we then parse and adapt.

**Comment by mcjaeger** [comment]
So, it would  be OK to have

* path name of the file
* file hash., sha1 I assume
* detected license expression
* type of scan algorithm used

?

**Comment by jeffmcaffer** [comment]
in the end all we need is the path and the license results. the other information may be useful in some scenarios but at least for now would not be included in the ClearlyDefined definition.

**Comment by jeffmcaffer** [comment]
Closing this one as we have the basic infrastructure in place. Need to add Copyright and Monk when they are independent of the fossology database/service
