### ISSUE TITLE
Explore getting SAS tokens for crawler

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#104]
We'd like to enable some specific, trusted people to be able to queue things for crawling, harvesting and scanning. To do this we'd like to explore the feasbility and implementation requirements for giving some SAS tokens to these people. 

@jeffmcaffer for visibility

**Comment by geneh** [comment]
### Minimal set of permissions:
Allowed services:
- [x] Blob
- [x] Queue

Allowed resource types:
- [x] Container
- [x] Object

Allowed permissions:
- [x] Read
- [x] Write
- [x] Add
- [x] Process

**Comment by jeffmcaffer** [comment]
Awesome. Can you document this somewhere in the Crawler doc? Perhaps just the readme or some such.
