### ISSUE TITLE
Identify and scan top 1k packages in PyPi

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#108]
Once we've completed the integration of the PyPi package manager, we want to figure out what the top 1,000 packages in PyPi are and harvest and scan them.

**Comment by jeffmcaffer** [comment]
From a PyPi-knowledgeable person...

From what I’ve been able to determine, PyPI’s downloads counts were deprecated in 2013 and removed earlier this year. There is now an alternative source for that information though. There is a project called “Linehaul” (https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html) that is inserting all PyPI download events into a publicly accessible Google BigQuery database. This is directly query-able, but does require a Google account and starts costing money if you query more than 1TB per month.
  
This project automates the interaction with the above data in BigQuery (in Python), but still requires a Google account:https://github.com/ofek/pypinfo
  
This project leverages the above automation and has a weekly dump of the top 5000 PyPI projects in json format: https://github.com/hugovk/top-pypi-packages. Direct links to the json files:
* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.json
* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.json

**Comment by jeffmcaffer** [comment]
There is also https://bigquery.cloud.google.com/dataset/the-psf:pypi from Dustin at Python
