### ISSUE TITLE
Add crawler support for Launchpad (Ubuntu)

### ISSUE THREAD

**Issue by craigez** [clearlydefined/crawler#111]
Example API call and response:

https://api.launchpad.net/1.0/aafigure

`{"license_info": null, "remote_product": null, "recipes_collection_link": "https://api.launchpad.net/1.0/aafigure/recipes", "development_focus_link": "https://api.launchpad.net/1.0/aafigure/trunk", "bug_supervisor_link": null, "private": false, "registrant_link": "https://api.launchpad.net/1.0/~zsquareplusc", "official_bug_tags": [], "active_milestones_collection_link": "https://api.launchpad.net/1.0/aafigure/active_milestones", "commercial_subscription_is_due": false, "translation_focus_link": null, "licenses": ["Simplified BSD Licence"], "all_milestones_collection_link": "https://api.launchpad.net/1.0/aafigure/all_milestones", "bug_reporting_guidelines": null, "bug_reported_acknowledgement": null, "display_name": "aafigure", "wiki_url": null, "title": "aafigure", "homepage_url": "http://packages.python.org/aafigure", "download_url": null, "name": "aafigure", "is_permitted": "tag:launchpad.net:2008:redacted", "vcs": "Bazaar", "reviewer_whiteboard": "tag:launchpad.net:2008:redacted", "self_link": "https://api.launchpad.net/1.0/aafigure", "information_type": "Public", "resource_type_link": "https://api.launchpad.net/1.0/#project", "programming_language": "Python", "description": "An Ubuntu package is available: https://launchpad.net/~aafigure-team/+archive/ppa\n\nThe project is also registered in PyPi: http://pypi.python.org/pypi/aafigure\n\nManual and example document: http://launchpad.net/aafigure/trunk/0.5/+download/aafigure.pdf or click at the \"Home Page\" link below for the HTML version.\n", "project_reviewed": "tag:launchpad.net:2008:redacted", "brand_link": "https://api.launchpad.net/1.0/aafigure/brand", "sourceforge_project": null, "http_etag": "\"497cb12ff1f2ff73968809d42585e2853369ff47-ca122de12ac703ac1333205477def6e73b096221\"", "project_group_link": null, "date_created": "2009-06-11T13:13:47.154439+00:00", "active": true, "private_bugs": false, "bug_tracker_link": null, "security_contact": null, "license_approved": "tag:launchpad.net:2008:redacted", "driver_link": null, "freshmeat_project": null, "screenshots_url": null, "web_link": "https://launchpad.net/aafigure", "summary": "ASCII art figures can be parsed and output as SVG, PNG, JPEG, PDF and more. This project provides a python package and a command line script.", "logo_link": "https://api.launchpad.net/1.0/aafigure/logo", "owner_link": "https://api.launchpad.net/1.0/~aafigure-team", "qualifies_for_free_hosting": true, "releases_collection_link": "https://api.launchpad.net/1.0/aafigure/releases", "date_next_suggest_packaging": null, "series_collection_link": "https://api.launchpad.net/1.0/aafigure/series", "commercial_subscription_link": null, "icon_link": "https://api.launchpad.net/1.0/aafigure/icon"}`

**Comment by fossygirl** [comment]
@craigez Closing this for now, please feel free to reopen if we decide to continue work here.
