### ISSUE TITLE
npm start does not work on Windows

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#115]
A recent change to package.json causes the crawler to fail to start on windows.

```
    "start": "CRAWLER_SERVICE_PORT=5000 node ./run.js",
```
That is format for setting and env var and running a command is not valid on Windows. 

Question, is this really needed? to make 5000 the default we should not need to set it anywhere. 

In particular, if we revert this change now does it break the cloud/docker deployments? In theory they should be getting set anyway since the Dockerfile includes ```ENV PORT 5000``` which should be equivalent.

**Comment by jeffmcaffer** [comment]
@geneh I did a quick fix in #116 to enable a smoother hackathon experience. See what you think but no need to spend a lot of time on it. If you are happy, close this. Ultimately we need the ghcrawler code to be a bit more flexible but that's a ways off.

**Comment by geneh** [comment]
Thanks! https://github.com/Microsoft/ghcrawler/commit/51fd988 did the trick.
