### ISSUE TITLE
Rename blobs based on new package manager casing

### ISSUE THREAD

**Issue by Teju-Manchenella** [clearlydefined/crawler#123]
All blob paths have been lower cased when stored in blob storage. Fix the blob storage paths so they match the names of the packages based on the new package manager casings. The specific package managers that will need attention at git (name/namespace), nuget (name/namespace), and maven (revision).

Along with that make sure that there is not duplicated harvested data or definitions due to new case. For example there should not be two blobs for Microsoft/TypeScript and microsoft/typescript.

**Comment by geneh** [comment]
Another thing to consider is the blobs' contents, for example the following fields would have to be updated as well:
```
    "type": "nuget",
    "url": "cd:/nuget/nuget/-/newtonsoft.json/11.0.2",
    "fetchedAt": "2018-08-02T22:29:07.435Z",
    "links": {
      "self": {
        "href": "urn:nuget:nuget:-:newtonsoft.json:revision:11.0.2:tool:clearlydefined:1",
        "type": "resource"
      },
      "siblings": {
        "href": "urn:nuget:nuget:-:newtonsoft.json:revision:11.0.2:tool:clearlydefined",
        "type": "collection"
      },
      "source": {
        "href": "urn:git:github:jamesnk:newtonsoft.json:revision:c4af75c8e91ca0d75aa6c335e8c106780c4f7712",
        "type": "resource"
      }
    },
```
Maybe it's simpler to delete some of the blobs and re-crawl.

**Comment by jeffmcaffer** [comment]
done
