### ISSUE TITLE
Enhance the list of interesting files

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#127]
The crawler can capture the content of *interesting* files (e.g., LICENSE). Currently it captures just a few. ScanCode looks at bigger list as interesting. 
```javascript
      const filenames = [
        'agreement',
        'copying',
        'copyleft',
        'copyright',
        'copyrights',
        'eula',
        'license',
        'licenses',
        'licensing',
        'licence',
        'licences',
        'licencing',
        'legal',
        'notice',
        'notices',
        'patent',
        'patents'
      ]
```
Typically a given component has only one or two of these files but we need to look for all just in case.

Note that that current implementation uses `glob` to look at the file system. It appears that this is quite expensive if you construct a glob expression that can handle all the variations between these files and the possible extensions. We need to either change the way the glob expression is structured or use a different approach. For example, we can leverage the following to do something really simple

1. we are only looking at the root folder of the component
2. The list of files above is large but not that large. Could just generate all the combinations and do a simple dir list, toLowerCase and then intersect.

Note also that we should include `.rst` as another possible extension

**Comment by nellshamrell** [comment]
Hello @dabutvin! I noticed you pushed some commits to your branch that would fix this issue, were those commits every submitted in a pull request?

**Comment by dabutvin** [comment]
👋 
They were! https://github.com/clearlydefined/crawler/pull/264

**Comment by nellshamrell** [comment]
Awesome @dabutvin! Thank you!

Closing this issue.
