### ISSUE TITLE
nomos fossology output contains temp directory

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#134]
The output looks like this when decoded:

```
File /tmp/cd-bnzDtH/package/LICENSE contains license(s) MIT
File /tmp/cd-bnzDtH/package/index.js contains license(s) MIT
File /tmp/cd-bnzDtH/package/README.md contains license(s) Microsoft-possibility
File /tmp/cd-bnzDtH/package/package.json contains license(s) MIT
```

This contains the temp directory that the package is unpacked into `this.options.installDir`

it should look like this:

```
File package/LICENSE contains license(s) MIT
File package/index.js contains license(s) MIT
File package/README.md contains license(s) Microsoft-possibility
File package/package.json contains license(s) MIT
```

If there is an option in Nomos to modify this, we should prefer that, otherwise we should post-process to normalize the path

**Comment by larainema** [comment]
Nomos have two types of output:
1. include the full file path
2. just the file name
I think we should use the full file path and post-process to normalize the path, as if we just use the file name, we can not distinguish the file with same file name.

**Comment by dabutvin** [comment]
@larainema makes sense to use the full file path and post-process 👍

**Comment by jeffmcaffer** [comment]
done
