### ISSUE TITLE
delete weird nuget blobs

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#143]
An old version of the crawler did not correctly manage nuget versions (they do not allow trailing .0 in the 4th segment or leading 0s in segments). This has been updated and all the affected components reharvested. Now we need to delete all the old blobs. See the attached file (had to zip as .json is not supported)

Note that all the blobs to be deleted will need /tool/clearlydefined/1.json appended

[nugetRequests.zip](https://github.com/clearlydefined/crawler/files/2321129/nugetRequests.zip)

This is in support of https://github.com/clearlydefined/service/pull/198

**Comment by dabutvin** [comment]
this is done
