### ISSUE TITLE
validate ScanCode result for react-redux (and others) crawling

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#148]
The ScanCode result corresponding to https://github.com/reduxjs/react-redux/tree/85145c2a8d3e0d49eb90fe561141ad57530a2603
Shows only three files but the repo has many. Sup with that?

**Comment by fossygirl** [comment]
@dabutvin Can you check out if the new version of ScanCode addresses this?

**Comment by dabutvin** [comment]
came across a ui bug looking at this. Let's leave this open to see if that fixes it when it rolls out.

Check https://clearlydefined.io/definitions/git/github/reduxjs/react-redux/85145c2a8d3e0d49eb90fe561141ad57530a2603 sometime next week

**Comment by dabutvin** [comment]
this is fixed
