### ISSUE TITLE
Update PyPi support

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#153]
Some comments from a PyPi knowledgeable person on the PyPi integration.

* I think `_getRevision` should just use the top-level `version` attribute (`info.version`) returned from PyPI rather than trying to determine the latest release from the keys in the releases dictionary. The current implementation assumes a specific ordering that the real-world data does not look to be following consistently. See the entry for `pip` on https://dev.clearlydefined.io/definitions for an example where it is pulling the wrong version.
* It doesn't look like the `source` field is getting populated. There are a few options for where you may be able to pull that URL from. 
   * One is the `info.descriptions` entry. Sometimes a link to a host repo will be embedded within there. It's free-form text though, and often there will be other links present as well, making parsing it a tricky proposition.
   * Another would be to use the entry in the top-level `info.urls` list that has its `packagetype` set to `sdist` or `python_version` set to `source`. The `url` value for that entry will be a link to a tarball containing a source distribution of the package.
   * Similarly, you could walk through the list in `info.releases` associated with the `version` determined in the first bullet point and get the `url` value for the entry with `packagetype: sdist` or `python_version: source`, if any.
* For the license attribute, I'd consider just using the top-level `info.license` value rather than parsing it from the classifiers. Alternatively, it could fall back on the licenses parsed from the classifiers if it is missing from `info.license` or maybe be the union of the two. Also, the current parsing logic will only find licenses tagged as "OSI Approved" by the package maintainer. That may be too restrictive for what you're trying to accomplish, though I'm not sure. It could be made more inclusive by returning all entries that start with "License :: ".

**Comment by nellshamrell** [comment]
Closing this due to the age of the issue. If anyone would like to discuss this more, please feel free to re-open this issue.
