### ISSUE TITLE
Duplicate deadletters getting logged

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#159]
All the dead letters that are showing up are added in pairs.

Cracking a pair open side by side shows that they are only 2 microseconds apart.

We must be logging the failure twice somewhere.

**Comment by dabutvin** [comment]
we are also getting double logging of traces, such as appInitStart - may be related

**Comment by fossygirl** [comment]
@dabutvin Another bug in your ear to possibly investigate before we re-queue everything and get double deadletters for everything?

**Comment by nellshamrell** [comment]
Closing this due to the age of the issue. If anyone sees this in the future, please feel free to re-open.
