### ISSUE TITLE
make it easy to identify crawlers

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#160]
Now that we have multiple clouds running crawlers one multiple k8s pods, it would be useful to be able to tell one from the other in the logs. To that end we propose adding two new properties to all telemetry messages

* `participant` -- a string identifying the organization running the crawler (e.g., Google, Microsoft, ...). This should be set explicitly via the new `CRAWLER_PARTICIPANT` environment variable.
* `deployment` -- a unique id for the deployment of the crawler. This value can be set using the new `CRAWLER_DEPLOYMENT` env var. For example, it may be the k8s pod name. If not set explicitly, the value should default to a GUID initialized on process start.

These property values can be set in the `meta` property of the request being processed. That way they will be carried through all related telemetry.

**Comment by jeffmcaffer** [comment]
@dabutvin we need to look at if we can assign different values to CRAWLER_DEPLOYMENT when deploying on app service and scaling out. We could just use the GUID fallback but if there is some useful Azure node corelator, that would be cool.

**Comment by dabutvin** [comment]
fixed in #200
