### ISSUE TITLE
[Scancode] Failed to setup plugin errors

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#162]
We've seen this error occur on the crawler 200+ times in the last week of crawling.
Not sure if it is based on the package or some other basis.

Here is an example of the error output:

<summary>
<details>

```
Error: Command failed: cd /opt/scancode-toolkit-2.9.2 && ./scancode --copyright --license --info --package --license-diag --only-findings --strip-root --timeout 1000 -n 2 --json-pp /tmp/cd-LOAq2S /tmp/cd-5biutd/iotivity Setup plugins... 

ERROR: failed to setup plugin: scan:licenses: Traceback (most recent call last): File "/opt/scancode-toolkit-2.9.2/src/scancode/cli.py",
  line 568, in scancode plugin.setup(**kwargs) File "/opt/scancode-toolkit-2.9.2/src/scancode/plugin_license.py",
  line 127, in setup return_value=False) File "/opt/scancode-toolkit-2.9.2/src/licensedcode/cache.py",
  line 64, in get_index _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency) File "/opt/scancode-toolkit-2.9.2/src/licensedcode/cache.py",
  line 181, in get_cached_index with yg.lockfile.FileLock(lock_file, timeout=timeout): File "/opt/scancode-toolkit-2.9.2/local/lib/python2.7/site-packages/yg/lockfile/__init__.py",
  line 43, in __enter__ self.acquire() File "/opt/scancode-toolkit-2.9.2/local/lib/python2.7/site-packages/yg/lockfile/__init__.py",
  line 99, in acquire raise FileLockTimeout() FileLockTimeout
 at ChildProcess.exithandler (child_process.js:275:12)
 at emitTwo (events.js:126:13)
 at ChildProcess.emit (events.js:214:7)
 at maybeClose (internal/child_process.js:925:16)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) killed: false, code: 2, signal: null, 
 
 cmd: 'cd /opt/scancode-toolkit-2.9.2 && ./scancode --copyright --license --info --package --license-diag --only-findings --strip-root --timeout 1000 -n 2 --json-pp /tmp/cd-LOAq2S /tmp/cd-5biutd/iotivity'
```

</details>
</summary>

---

This is a sample of 50 coordinates to try and repro the failure:

<summary>
<details>

 - git/github/acl-dev/acl/175623b306048ecaa47aee452149f4c7aba2181a	
 - git/github/alibaba/alisql/c25864677532607ff60c71198b430fbee82f84fa	
 - git/github/dotnet/corefx/6c6b536dffb4da0c45ff14921bfee10265265050	
 - git/github/grame-cncm/faust/2a0772ef9ac59819cab889823c87aad6c4028cfd	
 - git/github/llvm-mirror/test-suite/ee28064127f011db5b518c98ae4503b144ab8503	
 - git/github/microsoft/directxshadercompiler/e49d495f94669c1969d9b88d62d0e525a820fd92	
 - git/github/microsoft/winobjc/f32939638b35246e971ac775fe6e9c7780449455	
 - npm/npmjs/-/ajv/5.1.6	
 - npm/npmjs/-/buffer-from/1.1.1	
 - npm/npmjs/-/canvas-fit/1.5.0	
 - npm/npmjs/-/coffeescript/1.10.0	
 - npm/npmjs/-/color/2.0.1	
 - npm/npmjs/-/ecc-jsbn/0.1.2	
 - npm/npmjs/-/element-size/1.1.1	
 - npm/npmjs/-/esprima/4.0.1	
 - npm/npmjs/-/expect.js/0.2.0	
 - npm/npmjs/-/get-canvas-context/1.0.2	
 - npm/npmjs/-/gl-format-compiler-error/1.0.3	
 - npm/npmjs/-/gl-mesh3d/2.0.0	
 - npm/npmjs/-/glsl-inverse/1.0.0	
 - npm/npmjs/-/glsl-specular-beckmann/1.1.2	
 - npm/npmjs/-/glsl-token-scope/1.1.2	
 - npm/npmjs/-/grunt-tslint/5.0.2	
 - npm/npmjs/-/gulp-xml2json/0.1.5	
 - npm/npmjs/-/hoek/5.0.4	
 - npm/npmjs/-/is-svg-path/1.0.2	
 - npm/npmjs/-/kdbush/1.0.1	
 - npm/npmjs/-/mat4-recompose/1.0.4	
 - npm/npmjs/-/normals/1.1.0	
 - npm/npmjs/-/oauth-sign/0.9.0	
 - npm/npmjs/-/office-ui-fabric-react/6.17.0	
 - npm/npmjs/-/p-is-promise/1.1.0	
 - npm/npmjs/-/parse-svg-path/0.1.2	
 - npm/npmjs/-/pick-by-alias/1.2.0	
 - npm/npmjs/-/postcss-nesting/4.2.1
 - npm/npmjs/-/rcedit/0.9.0	
 - npm/npmjs/-/react-test-renderer/16.5.1	
 - npm/npmjs/-/request/2.88.0	
 - npm/npmjs/-/robust-determinant/1.1.0	
 - npm/npmjs/-/robust-subtract/1.0.0	
 - npm/npmjs/-/semver/5.5.1	
 - npm/npmjs/-/toxic/1.0.1	
 - npm/npmjs/-/two-product/1.0.2	
 - npm/npmjs/-/upath/1.0.5	
 - npm/npmjs/-/v8flags/3.0.2	
 - npm/npmjs/@babel/helper-function-name/7.0.0-beta.49	
 - npm/npmjs/@babel/helper-get-function-arity/7.0.0-beta.49	
 - npm/npmjs/@babel/helper-split-export-declaration/7.0.0-beta.49	
 - npm/npmjs/@babel/template/7.0.0-beta.49	
 - npm/npmjs/@plotly/d3-sankey/0.5.0	

</details>
</summary>

**Comment by fossygirl** [comment]
@dabutvin Depending on what your investigation reveals, @pombredanne may be able to help and/or have you open an issue on https://github.com/nexB/scancode-toolkit.

**Comment by pombredanne** [comment]
@dabutvin thank you for the report!

This is a timeout to acquire a lock file when executing the setup of the ScanCode license plugin ... e.g. this  builds the index used for license detection if the index does not exist on disk. 

A lock file is used such that index building is done exclusively by only one process or thread system-wide. The lock value is [240 seconds](https://github.com/nexB/scancode-toolkit/blob/e23b1d79f7e86ae48e746aeeae8fd85c93ecb1c4/src/licensedcode/cache.py#L53) and this happens [here](https://github.com/nexB/scancode-toolkit/blob/e23b1d79f7e86ae48e746aeeae8fd85c93ecb1c4/src/licensedcode/cache.py#L184)

So what could be the reason for this timeout? It can occur only if there were several ScanCode processes running at the same time and this was the first time ever that ScanCode was being run in this system container.

This typically should be never happen in a production setting: the index should have been created in the container image during its build (e.g. part of the Dockerfile ?) and ScanCode should never go in this code segment unless there are some serious underlying system issues such as disappearing files. 

So this is likely the sign that we should review the config and update this.
The container used is built [here](https://github.com/clearlydefined/crawler/blob/711a25c4efb9cade78816baeb89b53fadb1caf29/Dockerfile#L11) afaik and we should IMHO ensure that the license detection index is created at build time only once, and not at runtime.
Add a new line such as `RUN /opt/scancode-toolkit-2.9.2/scancode --reindex-licenses` would do this alright. 

With this:
1. the scans should run much faster as the index is never rebuilt at scan time
2. there should never be contention with lock files involved at scan time

**Comment by dabutvin** [comment]
Hey thanks for the great info. I just gave it a shot in #169 and it looks good from what I can tell

Before:

```
docker build --rm -f "Dockerfile" -t crawler:dan1 .
Sending build context to Docker daemon  1.577MB
Step 1/24 : FROM node:8
 ---> ed145ef978c4
Step 2/24 : ENV APPDIR=/opt/service
 ---> Running in da805f095d03
Removing intermediate container da805f095d03
 ---> edfa6bde59e7
Step 3/24 : RUN curl -sL https://github.com/nexB/scancode-toolkit/releases/download/v2.9.2/scancode-toolkit-2.9.2.tar.bz2 | tar -C /opt -jx   && /opt/scancode-toolkit-2.9.2/scancode --version
 ---> Running in fca6c125b772
* Configuring ScanCode for first use...
ScanCode version 2.9.2
Removing intermediate container fca6c125b772
 ---> d0b6aff7065b
Step 4/24 : ENV SCANCODE_HOME=/opt/scancode-toolkit-2.9.2
 ---> Running in befa23b53cee
Removing intermediate container befa23b53cee
 ---> 4648260a56f2
```


After:

```
docker build --rm -f "Dockerfile" -t crawler:dan2 .
Sending build context to Docker daemon  1.577MB
Step 1/24 : FROM node:8
 ---> ed145ef978c4
Step 2/24 : ENV APPDIR=/opt/service
 ---> Using cache
 ---> edfa6bde59e7
Step 3/24 : RUN curl -sL https://github.com/nexB/scancode-toolkit/releases/download/v2.9.2/scancode-toolkit-2.9.2.tar.bz2 | tar -C /opt -jx   && /opt/scancode-toolkit-2.9.2/scancode --reindex-licenses   && /opt/scancode-toolkit-2.9.2/scancode --version
 ---> Running in 99cbfd70c098
* Configuring ScanCode for first use...
Checking and rebuilding the license index...
Done.
ScanCode version 2.9.2
Removing intermediate container 99cbfd70c098
 ---> a8633a7cd65b
Step 4/24 : ENV SCANCODE_HOME=/opt/scancode-toolkit-2.9.2
 ---> Running in ab89e3e5d73f
Removing intermediate container ab89e3e5d73f
 ---> dffc826df303
```
