### ISSUE TITLE
Many temp 503s from Maven search

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#182]
503 Service Temporarily Unavailable

we are hitting urls like 

 - https://search.maven.org/solrsearch/select?q=g:"commons-logging"+AND+a:"commons-logging"+AND+v:"1.1"&rows=1&wt=json

We are probably overloading the server, we could add some kind of throttle or retry backoff policy

**Comment by dabutvin** [comment]
this is still an issue for getting poms using something like https://search.maven.org/remotecontent?filepath=com/weicoder/redis/3.0.0/redis-3.0.0.pom

**Comment by dabutvin** [comment]
we could try using a different url like: https://repo1.maven.org/maven2/com/weicoder/redis/3.0.0/redis-3.0.0.pom

this may be more direct

**Comment by nellshamrell** [comment]
At this time I cannot reproduce this. If anyone sees this in the future, please feel free to re-open this and we will investigate further.
