### ISSUE TITLE
Investigate components that we can't harvest

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#190]
We tried harvesting the following components:

"git/github/asm/asm/8b56cad44ffb6809306ef3f0051b7495f8ae267b"
"git/github/axorg/ace-builds/21f7fa46ece12f8c425a5563784b3bf3fe84117d"
"git/github/klarsys/angular-materia-l-icons/b07d0581d7481be57b01799a6f917c554e874e2b"
"git/github/lz4/lz4-java/7bb64ff2b69a9f8367de9ab483cdadf42b4c1b65"
"git/github/salmonbrys/anr-watchdog/5d360be708ee17327ce87d48f98c22f9043ca3aa"
"git/github/x-stream/x-stream/6acae3f1c9a6ab94e78d0bb0e39429c120fcd718"
"maven/mavencentral/external/aopalliance-repackaged/2.4.0-b09"
"maven/mavencentral/hk2/osgi-resource-locator/1.0.1"
"maven/mavencentral/hsqldb/hsqldb/2.3.3"
"maven/mavencentral/jopt-simple/jopt-simple/3.2"
"maven/mavencentral/mail/mail/1.5.0-b01"
"maven/mavencentral/mock-server/mockserver-netty/3.9.1"
"maven/mavencentral/mockito/mockito-core/2.0.30-beta"
"maven/mavencentral/mozilla/rhino/1.7R5"
"maven/mavencentral/net.sf.barcode4/barcode4j/2.1"
"maven/mavencentral/netty/netty/3.10.4.Final"
"maven/mavencentral/oval /oval/1.85"
"maven/mavencentral/ri/jax-rs-ri/1.9-ea07"
"maven/mavencentral/xpp3/xpp3_min/1.1.4"

and we're able to do so successfully. Can we investigate why?

**Comment by dabutvin** [comment]
these are all 404s

- https://github.com/asm/asm/commit/8b56cad44ffb6809306ef3f0051b7495f8ae267b
- https://github.com/axorg/ace-builds/commit/21f7fa46ece12f8c425a5563784b3bf3fe84117d
- https://github.com/klarsys/angular-materia-l-icons/commit/b07d0581d7481be57b01799a6f917c554e874e2b
- https://github.com/lz4/lz4-java/commit/7bb64ff2b69a9f8367de9ab483cdadf42b4c1b65
- https://github.com/salmonbrys/anr-watchdog/commit/5d360be708ee17327ce87d48f98c22f9043ca3aa
- https://github.com/x-stream/x-stream/commit/6acae3f1c9a6ab94e78d0bb0e39429c120fcd718
- https://search.maven.org/artifact/external/aopalliance-repackaged/2.4.0-b09/jar
- https://search.maven.org/artifact/hk2/osgi-resource-locator/1.0.1/jar
- https://search.maven.org/artifact/hsqldb/hsqldb/2.3.3/jar
- https://search.maven.org/artifact/jopt-simple/jopt-simple/3.2/jar
- https://search.maven.org/artifact/mail/mail/1.5.0-b01/jar
- https://search.maven.org/artifact/mock-server/mockserver-netty/3.9.1/jar
- https://search.maven.org/artifact/mockito/mockito-core/2.0.30-beta/jar
- https://search.maven.org/artifact/mozilla/rhino/1.7R5/jar
- https://search.maven.org/artifact/net.sf.barcode4/barcode4j/2.1/jar
- https://search.maven.org/artifact/netty/netty/3.10.4.Final/jar
- https://search.maven.org/artifact/oval/oval/1.85/jar
- https://search.maven.org/artifact/ri/jax-rs-ri/1.9-ea07/jar
- https://search.maven.org/artifact/xpp3/xpp3_min/1.1.4/jar

**Comment by fossygirl** [comment]
@dabutvin Okay, I'm closing this since I don't think there's anything further we can do here.
