### ISSUE TITLE
collect file hashes

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#221]
We need to collect and surface (on the definitions) the hash of each file that is scanned. 

* some of the tools we are using now (scancode) may already be doing this
* we need to agree on a hash algorithm to use. Something common (e.g., Git, Software Heritage, ...)

**Comment by dabutvin** [comment]
Maybe we should collect multiple hashes at the same time.

Software Heritage captures SHA-1, SHA-1 Git, SHA-256 today.

**Comment by dabutvin** [comment]
scancode does sha1 and md5 in version 2.9.2

```
"path": "package/elastic.js",
"type": "file",
"name": "elastic.js",
"base_name": "elastic",
"extension": ".js",
"size": 7946,
"date": "2015-07-17",
"sha1": "d6d5070a64a79b9e86791cc5734c8fdb418d5307",
"md5": "6b70e3454fd4e45290ddd9936bd37852",
"mime_type": "text/plain",
"file_type": "ASCII text",
"programming_language": "JavaScript",
"is_binary": false,
"is_text": true,
"is_archive": false,
"is_media": false,
"is_source": true,
"is_script": false,
```
