### ISSUE TITLE
Add support for https://packagist.org/

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#230]
Packagist is the main Composer repository. It aggregates public PHP packages installable with Composer.

This is referenced on the top libraries from libraries.io

**Comment by Fredrick-Tam** [comment]
Would be awesome if this could be in the pipeline in the next 1-3 months. ❤️

**Comment by jeffmcaffer** [comment]
@Fredrick-Tam do you know anyone with Packagist expertise who can guide this implementation? Typically we need someone who understands the packaging ecosystem (where licenses are declared, how the API works, ...). With that info it is quite easy to implement all the integrations. Without we end up guessing and getting it wrong a bunch.

**Comment by Fredrick-Tam** [comment]
Not that I know of but I can look into that once we get the majority of desired package managers we are currently processing.

**Comment by geneh** [comment]
It has been addressed.
