### ISSUE TITLE
[Fossology] Copyright tool has lots of failures

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#253]
We are getting a big batch of these failures each day. It _may_  be kicking out based on file extensions

here's a small sample

```

Command failed: cd /opt/fossology/src/copyright/agent && ./copyright --files /tmp/cd-w7XBQt/package/ios/Vendor/SDWebImage/SDWebImage.xcodeproj/xcshareddata/xcschemes/SDWebImage watchOS.xcscheme -J
--
Command failed: cd /opt/fossology/src/copyright/agent && ./copyright --files /tmp/cd-bWPBvw/angular.js/docs/content/error/$compile/iscp.ngdoc -J
--
Command failed: cd /opt/fossology/src/copyright/agent && ./copyright --files /tmp/cd-w7XBQt/package/ios/Vendor/SDWebImage/Examples/SDWebImage Watch Demo Extension/Assets.xcassets/README__ignoredByTemplate__ -J



```

This is because we are throwing and marking dead on every file that fails.

We should not markdead in the fossology processor at individual file levels, we should make best effort to get any tool output.

We should run a couple of these cases and see what the error cases are, maybe we can handle different error codes specially.

Log some telemetry instead of errors so we can follow up.

**Comment by geneh** [comment]
Closing this one since fossology has been disabled. Please re-open if needed.
@fossygirl FYI
