### ISSUE TITLE
[maven] Haven't run all tools

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#279]
For example, on components: restfb and junit-jupiter-api for maven we have only run the ClearlyDefined tools and haven't run any of our other tools. Why?

@dabutvin

**Comment by pombredanne** [comment]
This is something I meant to report too.

**Comment by pombredanne** [comment]
from @dabutvin

> It looks like this is the way the crawler is setup https://github.com/clearlydefined/crawler/blob/master/providers/process/mavenExtract.js#L36

@bduranc ping too

**Comment by dabutvin** [comment]
so we should run scancode/fossology/licensee on the extracted jar/aar files?
example: https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar

Anything else?

**Comment by pombredanne** [comment]
@dabutvin for a start this is it. Do we have also the source jar?

**Comment by dabutvin** [comment]
today, the source jar gets picked up with different coordinates

- https://clearlydefined.io/definitions/maven/mavencentral/com.fasterxml.jackson.core/jackson-core/2.8.5
- https://clearlydefined.io/definitions/sourcearchive/mavencentral/com.fasterxml.jackson.core/jackson-core/2.8.5
