### ISSUE TITLE
No files for a maven that has files

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#281]
We think the maven crawler might not be working right. Take a look at 

https://clearlydefined.io/definitions/sourcearchive/mavencentral/com.amazonaws/aws-java-sdk/1.11.271

You'll see we found no files even though this package probably does. 

@dabutvin

**Comment by dabutvin** [comment]
working through https://clearlydefined.io/definitions/maven/mavencentral/com.amazonaws/aws-java-sdk/1.11.271

we get the pom and it's parent from 
 - https://search.maven.org/remotecontent?filepath=com/amazonaws/aws-java-sdk-pom/1.11.271/aws-java-sdk-pom-1.11.271.pom
 - https://search.maven.org/remotecontent?filepath=com/amazonaws/aws-java-sdk/1.11.271/aws-java-sdk-1.11.271.pom

we read the `packaging=pom` so when we fetch the artifact we fetch the pom and try to unzip it, which I don't think makes much sense.

I think we can't trust the inheritance of this packaging node and we should just try to fetch the jar or aar as we find them.

![image](https://user-images.githubusercontent.com/5168796/55520563-c4ffde80-5631-11e9-8ed5-fbc036ed9493.png)

**Comment by jeffmcaffer** [comment]
Do you think the jar/aar will have reliably have the POM in it? Do we really need the POM itself? also, can we fix the fetch to not try and unzip POM packagings (we presumably know we're fetching a POM vs a JAR)

**Comment by dabutvin** [comment]
I think we should still get the poms and do the merge separately

And then fetch and unzip the artifact. I was thinking about just trying to fetch all known binary extensions until we find one that doesn't 404 instead of trying to infer whether it's a jar or an aar

**Comment by jeffmcaffer** [comment]
Sounds good

**Comment by dabutvin** [comment]
fixed in #285
