### ISSUE TITLE
enhance recovery from fetch and other errors

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#30]
When fetching the NPM buffer-shims v1.0.0 we got a 500 error from the NPM service. See below. The fetcher (and other parts of the crawler that talk to remote services) should be enhanced to differentiate between transient (and thus retryable) errors and fatal errors.  For example 500s are presumably unexpected and may be some temporary network/service issue. These can be retried. 404s however are generally permanent.

```
[I] Error npm@cd:/npm/npmjs/-/buffer-shims/v1.0.0 500 Internal Server Error{"loopName":"0","cid":"13","root":"self","time":1741}

500 Server error

npmFetch.js:42
```

**Comment by dabutvin** [comment]
this is done.
We markSkip for 404s and move on while we fail and retry for other unexpected problems
