### ISSUE TITLE
cleanup old git data with shortened sha's

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#301]
before we landed https://github.com/clearlydefined/crawler/pull/258 we had a good bit of git data already harvested

We should go through and purge all the bogus data

example of the issue
https://clearlydefined.io/definitions/git/github/llvm/llvm-project/d2298e7
and
https://clearlydefined.io/definitions/git/github/llvm/llvm-project/d2298e74235598f15594fe2c99bbac870a507c59

(only the longer one should exist)

This is the initial thinking:

1. iterate all harvested git blobs if they have a revision coordinate segment less than 10 characters then delete them
2. iterate all definition git blobs if they have a revision coordinate segment less than 10 characters delete them
3. find and delete the shortened hash definitions from the mongo store
4. purge the shortened hashes definitions from the search index

**Comment by geneh** [comment]
After checking all the blobs, there are no git coordinates with revision commit hash less than 10 characters. A quick search against both Mongo store and search index hasn't returned any results for that too.
