### ISSUE TITLE
Violation of crates crawler policy

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#310]
The crawler is in violation of crates crawler policy which requires to restrict traffic to 1 request per second or less to avoid having the crawler blocked. Right now we're getting error 403 Forbidden.

https://crates.io/policies#crawlers
`We allow our API and website to be crawled by commercial crawlers such as GoogleBot. At our discretion, we may choose to allow access to experimental crawlers, as long as they limit their request rate to 1 request per second or less.`

It may require an introduction of a "slow" queue or a similar solution.

**Comment by nellshamrell** [comment]
At this time I cannot reproduce this. If anyone sees this in the future, please feel free to re-open this and we will investigate further.
