### ISSUE TITLE
Run ScanCode on NuGet package contents

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/crawler#311]
We originally didn't run ScanCode against NuGet package contents because they are mostly binaries, however, there are two scenarios where this would be useful:
1. The NuGet is re-packed script source (e.g. the jQuery NuGet)
1. The NuGet contains text files with license information

**Comment by geneh** [comment]
@iamwillbar Once the code is deployed, should any NuGet packages be re-queued, for example those with no license?

**Comment by iamwillbar** [comment]
@geneh as we discussed we should just queue all of the NuGets.
