### ISSUE TITLE
Not all tools are running on recently harvested components

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/crawler#320]
The following components were harvested last week (June 13), but as of today (June 17) only one tool (Licensee) has run on each:

https://clearlydefined.io/definitions/git/github/johanvos/openjdk-mobile11/19fb8f93c59dfd791f62d41f332db9e306bc1422

https://clearlydefined.io/definitions/git/github/jasminb/jsonapi-converter/197dc733d294a0fb7f346f7c72755b46d779bef6

**Comment by geneh** [comment]
clearlydefined/1.3.0, licensee/9.13.0, scancode/3.2.2 have run for https://clearlydefined.io/definitions/git/github/jasminb/jsonapi-converter/197dc733d294a0fb7f346f7c72755b46d779bef6

and clearlydefined/1.3.0, licensee/9.13.0 have run for https://clearlydefined.io/definitions/git/github/johanvos/openjdk-mobile11/19fb8f93c59dfd791f62d41f332db9e306bc1422.

There are now many messages in the queue, so there may be delays.

As for openjdk-mobile11's scancode, I see the following in the logs multiple times but the results do not end up going into the blob storage.
The Docker containers probably run out of memory, crash, and get re-started for this component. I'll check later to see if that's the case.
`Analyzing scancode@cd:/git/github/johanvos/openjdk-mobile11/19fb8f93c59dfd791f62d41f332db9e306bc1422 using ScanCode.`

**Comment by geneh** [comment]
The scancode process for git/github/johanvos/openjdk-mobile11/19fb8f93c59dfd791f62d41f332db9e306bc1422 runs out of memory and cannot be completed due to memory limitation. Closing for now.

**Comment by geneh** [comment]
Opened https://github.com/clearlydefined/crawler/issues/330 to address.
