### ISSUE TITLE
Source location not detected for NuGet component

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/crawler#323]
Component:
https://clearlydefined.io/definitions/nuget/nuget/-/Moq/4.7.7

The .nuspec points at the repository:
https://github.com/moq/moq4

And that repository has a tag for v4.7.7:
https://github.com/moq/moq4/releases/tag/v4.7.7

Based on this we should have been able to detect the source location automatically.

**Comment by geneh** [comment]
Which API have you used to retrieve .nuspec?
The one that's being used does not point to the source: https://api.nuget.org/v3-flatcontainer/moq/4.7.7/moq.nuspec

**Comment by geneh** [comment]
We should improve source location lookup for NuGet by checking the latest version if the current version does not contain this data.
