### ISSUE TITLE
remove heartbeat "GET"s from app insights

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#33]
Every 5 min there is a GET sent to the crawler service. Likely a health check or keep alive. That's fine but they should no appear in the logs or factor into the service request response times

**Comment by jeffmcaffer** [comment]
@iamwillbar or @geneh you guys know anything about how this works? I seem to remember there was a way to filter these out.

**Comment by iamwillbar** [comment]
We had a slightly different issue elsewhere, the AlwaysOn was hitting / which wasn't a valid route in the other service, so we just added a route that returned a 204 so you didn't see errors in the log.

For filtering them out they do use the User Agent "AlwaysOn", so you could filter that out. You can also filter out "synthetic traffic" in App Insights and I would expect that to filter these out.

**Comment by jeffmcaffer** [comment]
closing for now. its not the end of the world
