### ISSUE TITLE
getaddrinfo ENOTFOUND for Microsoft.Azure.DocumentDB.Core/2.9.3

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#374]
https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Azure.DocumentDB.Core/2.9.3
could not be harvested due to the following error:
```
Error nuget@cd:/nuget/nuget/-/Microsoft.Azure.DocumentDB.Core/2.9.3 getaddrinfo ENOTFOUND portalcontent.blob.core.windows.net

Error: getaddrinfo ENOTFOUND portalcontent.blob.core.windows.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
```
This is strange because the packageContent URL in https://api.nuget.org/v3/registration4-gz-semver2/microsoft.azure.documentdb.core/2.9.3.json seems to be correct.

**Comment by nellshamrell** [comment]
I tried running this locally and it does appear to be working now, so I'm going to close this. If anyone sees similar behavior, however, please feel free to re-open.
