### ISSUE TITLE
Clearly Defined Fails to fully harvest a component

### ISSUE THREAD

**Issue by clearlyoss** [clearlydefined/crawler#380]
When harvesting exoplayer in clearly defined the harvest returned a single file (the license file) and not the complete set of files.

Expectation: When harvesting the full set of files from the repo appears.

CD Link: https://clearlydefined.io/definitions/git/github/google/ExoPlayer/09d1e3e35d98fd02c31391ac1c891f0c73e76375 

Github link to the repo: https://github.com/google/ExoPlayer

**Comment by geneh** [comment]
I have re-harvested this component by going to https://clearlydefined.io > login if not logged in > harvest > search for the component version > harvest.
Please feel free to do it in the future.
Now the files appear as expected:
![Screen Shot 2020-03-09 at 9 36 42 AM](https://user-images.githubusercontent.com/1537662/76236164-83849580-61e9-11ea-8b53-0ca315c5c664.png)
