### ISSUE TITLE
Harvest issue with @ in component name

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/crawler#421]
Hi,

This package appears stuck in "Not harvested" mode - https://clearlydefined.io/definitions/npm/npmjs/types/gsap/1.20.0.  

It appears the @ part of the package name was dropped.  

The actual package is here: https://www.npmjs.com/package/**@types**/gsap/v/1.20.0

Thanks,
Ariel

**Comment by ariel11** [comment]
Found another one: https://clearlydefined.io/definitions/npm/npmjs/progress/kendo-data-query/1.5.1

"Not harvested" - and the real package name with an @  is *@progress*/kendo-data-query/v/1.5.1 (https://www.npmjs.com/package/@progress/kendo-data-query/v/1.5.1)

**Comment by ariel11** [comment]
Another example - https://clearlydefined.io/definitions/npm/npmjs/pm2/agent/2.0.0.  Missing @ in front of package name - https://www.npmjs.com/package/@pm2/agent

**Comment by capfei** [comment]
Closing this one since it looks like this has been resolved. When searching for these components, they all show up correctly with the `@` and are harvested.
