### ISSUE TITLE
The crawler queue has a lot of messages need to process

### ISSUE THREAD

**Issue by MichaelTsengLZ** [clearlydefined/crawler#425]
The ClearlyDefined crawler queue has around 306558 messages to be processed. However, the crawler consumes around 100 messages per minute. Is it normal? Or it's just because ClearlyDefined has a very high load and it needs to scale up.

![image](https://user-images.githubusercontent.com/20408623/113946625-b2d74e80-97bd-11eb-832b-40c2004c5a70.png)

**Comment by nellshamrell** [comment]
This appears to have been a one time (or at least, very rare thing). The crawler queue has had a normal load since. I am closing this, but will keep an eye on the queue and consider expanding the number of crawler instances that we have.
