### ISSUE TITLE
Add handling for gitlab components to the crawler

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/crawler#430]
# Implementation Plan

Continued from https://github.com/clearlydefined/service/issues/842

Based on the changes made in https://github.com/clearlydefined/crawler/pull/424/files

(Subject to change)

## Crawler

- [x] Add gitlab to [lib/sourceSpec.js#toUrl](https://github.com/clearlydefined/crawler/blob/df0dd126f899dcd8bb913a51e2fe85e7ba886bf9/lib/sourceSpec.js#L33)
- [x] Add test for gitlab to [test/unit/lib/sourceSpecTests.js](https://github.com/clearlydefined/crawler/blob/master/test/unit/lib/sourceSpecTests.js)

**Comment by tinvaan** [comment]
Hi @nellshamrell, can this issue be closed or is anything pending here?

**Comment by nellshamrell** [comment]
This can be closed :)
