### ISSUE TITLE
Adapt crawler to have deferred/delegated steps

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#5]
for things like running ScanCode, it would be very convenient to be able to run them on a build service like Travis, VSTS, Circle, ... This will help share some load and potentially enable others to pitch in resources.

Essentially when we go to run the tool, rather than running it inline, queue a build that 

* does the work,  
* puts the output in a blob somewhere
* queues a request with the crawler to process the output

This would also be useful if we wanted to run these long running tools on the same box as it would free up the crawler loop while the tool runs async out of proc.

**Comment by jeffmcaffer** [comment]
@geneh  has added a mechanism to run long scans as build steps that call back into the crawler when done. Now we need to take that data via a webhook and do the final processing/integration.

**Comment by geneh** [comment]
@jeffmcaffer I though I already did that here:
https://github.com/clearlydefined/crawler/pull/43/files#diff-1fc58e9cc624a318fb98652ab42accca
Is it different?

**Comment by jeffmcaffer** [comment]
Right. I was mixing two different scenarios. closing.
