### ISSUE TITLE
Harvested definition with incomplete results

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/crawler#504]
Issue Type: Bug
Issue Description:

I came across this component that has not been re-computed since 2018.

https://clearlydefined.io/definitions/git/github/yvasiyarov/gorelic/a9bba5b9ab508a086f9a12b8c51fab68478e2128

https://web.archive.org/web/20221122200237/https://clearlydefined.io/definitions/git/github/yvasiyarov/gorelic/a9bba5b9ab508a086f9a12b8c51fab68478e2128 (archived)

Scancode appears to have run, but only found one file (LICENSE.MD)

There also appears to be one curation on the definition.

I re-submit the harvest job. Logging an issue here for tracking/reference.

@qtomlinson @mpcen

**Comment by bduranc** [comment]
Just a friendly update:

I tried to [re-harvest](https://clearlydefined.io/harvest) the above component as well as [this second one](https://clearlydefined.io/definitions/git/github/yvasiyarov/newrelic_platform_go/b21fdbd4370f3717f3bbd2bf41c223bc273068e6), but found no luck.

**Comment by qtomlinson** [comment]
posted the following to harvest queue: https://api.clearlydefined.io/harvest?turbo=true
`    {
		"tool": "source",
		"coordinates": "git/github/yvasiyarov/newrelic_platform_go/b21fdbd4370f3717f3bbd2bf41c223bc273068e6"
	}
`

**Comment by qtomlinson** [comment]
> I tried to [re-harvest](https://clearlydefined.io/harvest) the above component as well as [this second one](https://clearlydefined.io/definitions/git/github/yvasiyarov/newrelic_platform_go/b21fdbd4370f3717f3bbd2bf41c223bc273068e6), but found no luck.

Result for the second one is available at https://clearlydefined.io/definitions/git/github/yvasiyarov/newrelic_platform_go/b21fdbd4370f3717f3bbd2bf41c223bc273068e6

**Comment by bduranc** [comment]
I agree this looks to be resolved now. Thanks!
