### ISSUE TITLE
Implement scancode "build" for crawler

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#6]
Take the current scancode docker images and configure it to

* already be started once (first start of scancode does a bunch of work)
* runs the scan
* puts the output in a blob somewhere
* calls the /harvest endpoint to trigger the ingestion and processing of the output.

**NOTE**  "builds" have outputs. As long as we can download these outputs via a URL, then the build can just post a request with the URL. Then the crawler can pull that content, process and store in blob storage. If we do this, rather than creating a tmp file for the output, scancode should be given a location in the builds "output" folder. That would then be made available via the normal built output fetch.

Alternatively, the "build" could queue a request that has the actual output in it as part of the payload. There are limits on the size of a queue entry but compressed and Base64 encoded the output might fit.  That would save us from having to manage blob storage.

**Comment by geneh** [comment]
Similar to the updated issue https://github.com/clearlydefined/crawler/issues/39
Closing as duplicate.
