### ISSUE TITLE
Add Crawler Support for Yocto recipes/layers

### ISSUE THREAD

**Issue by craigez** [clearlydefined/crawler#76]
Add crawler support for bitbake/yocto recipes. It would get the code from the specified SRC_URI and run analysis.

A few questions/thoughts:
What to do about patches? Assume we'd want to apply the patch before the scan. This could be tricky.
What to do about support for layers and entire builds? Eventually I imagine we'd want to be able to crawl an entire layer and then an entire build and all the layers within the build for a particular BSP. Seems like we would need to do single recipes first.

We should chat to some of the automotive people at OSLS and get their opinions as they would be one of the more interested consumers of curated data for Yocto builds. They were super keen last year to work out how to crowd source and scale our Yocto-LiD efforts.

**Comment by craigez** [comment]
@rashmichitrakar we should work out how to resource this.

**Comment by pombredanne** [comment]
> What to do about patches? Assume we'd want to apply the patch before the scan. 

I would tend to think that each should be scanned separately but both should be curated ideally together as related things. And this could mean that there are three items for curation: a package, patch(es), and package+patch(es) ?

@jeffmcaffer @geneh Would you know how to relate packages together?

**Comment by craigez** [comment]
I was just discussing with @rashmichitrakar this morning. I think we'd have data and curation for the upstream package (SRCURI or whatever) and the package+patches (the recipe). The patches don't really stand alone without the recipe & package. So I think you store data at the recipe unit. When reviewing you would need to understand the patch license and how they combine to get the recipe level data. I think there are some global rules as to how patches are licensed if not specified.

**Comment by fossygirl** [comment]
@craigez Closing, but please feel free to reopen.
