### ISSUE TITLE
releaseDate wrong on git entities in prod

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#77]
The `gitCloner` automatically gets the date of of the commit being cloned by running `git show -s --format=%cI` and then taking the output as a ISO date. This works fine on Windows. In prod (linux) the releaseDate is coming through as `%cI`, which look suspiciously like the command being run.

See (https://git-scm.com/docs/git-show)

Not sure if this is a difference in who `git` works on Linux or how node `exec` works in its handling of `stdout`. Either way, the result is wrong.

Need to verify the behavior on linux. Likely should look at all the other `exec`s to ensure they are not susceptible to the same root cause as here (whatever it ends up being).

Once this is fixed, we should requeue all the github components. There should be a way to do this with a policy that forces reprocessing. Have to think what that is. Otherwise we can delete the blobs and rerun.

**Comment by geneh** [comment]
`git show -s --format=%cI` works on Mac but not on Ubuntu (git version 2.14.1 vs 2.1.4). Interestingly, all other `--format` versions work. Changing from `git show -s --format=%cI` (strict ISO 8601 format) to `git show -s --format=%ci` (ISO 8601-like format) seems to solve the problem: https://github.com/clearlydefined/crawler/commit/923f2b1f56d2aeddc71a82a69a509812c237ef0e

I'll identify and queue all clearlydefined requests with the right policy:
```
{
  "type": "clearlydefined",
  "url": "cd:/git/github/<org>/<repo>/<commit>",
  "policy": "always"
}
```
