### ISSUE TITLE
ScanCode failures do not stop requeuing

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#8]
Seems like if a scancode run (eg on Facebook/react) fails, the crawler keeps requeuing the request. It is not even getting deadlettered after 6 tries. Really, it should get deadlettered right away as it is unlikely that another try will be any different

```
[I] Analyzing git@cd:/git/github/facebook/react/f1691813e381cac7587c09aefbebd5fa5cfaa21b/tool/scancode using ScanCode. input: C:\Users\jeffm\AppData\Local\Temp\cd-18340DB091h00CI4r.tmp output: C:\Users\jeffm\AppData\Local\Temp\cd-18340qHtCKKl7KzA0.tmp
trackException:

null: Error: { Error: Command failed: cd c:/installs/scancode-toolkit-2.2.1 && scancode --copyright,--license,--info,--diag,--only-findings, --strip-root,--quiet,--timeout,300,-n,3,-f,json-pp,C:\Users\jeffm\AppData\Local\Temp\cd-18340DB091h00CI4r.tmp,C:\Users\jeffm\AppData\Local\Temp\cd-18340qHtCKKl7KzA0.tmp
[I] Error git@cd:/git/github/facebook/react/f1691813e381cac7587c09aefbebd5fa5cfaa21b/tool/scancode Command failed: cd c:/installs/scancode-toolkit-2.2.1 && scancode --copyright,--license,--info,--diag,--only-findings, --strip-root,--quiet,--timeout,300,-n,3,-f,json-pp,C:\Users\jeffm\AppData\Local\Temp\cd-18340DB091h00CI4r.tmp,C:\Users\jeffm\AppData\Local\Temp\cd-18340qHtCKKl7KzA0.tmp
{"loopName":"0","cid":"41","root":"npm@cd:/npm/npmjs/-/react","attempt":1,"time":339734}
```

**Comment by jeffmcaffer** [comment]
This is likely a case where the requeued request is a new copy and is not carrying over the context which includes the retry count.

**Comment by pombredanne** [comment]
`scancode --copyright,--license,--info,--diag,--only-findings`

It sounds like  the commas in this command could be the source of the problem?

**Comment by jeffmcaffer** [comment]
Thanks @pombredanne. Interestingly, running the scancode command with the commas works on Windows. Does not work on Linux. Having the commas was a bug and completely unintended. @geneh found and fixed that yesterday.  It is not clear why scancode is erroring out on facebook/react. It works fine on the other top 20 NPMs. I also did not spend any time looking at the reason for that failure.

The particular problem in this issue has more to do with the error handling in the Crawler than scancode itself I suspect. When an error happens during processing, the crawler should assess the error and decide if it is transient or fatal. If transient, the request can be requeued and tried again. If fatal, the request should be deadlettered. In any event, even persistent but transient errors should only be retried at most 5 times and then deadlettered. In this case the crawler was continuously requeuing the request to scan react.

**Comment by geneh** [comment]
Now it goes to deadletter after 1 attempt:
```
    "extra": {
      "type": "source",
      "url":
        "cd:/git/github/facebook/react/f1691813e381cac7587c09aefbebd5fa5cfaa21b/tool/scancode",
      "reason":
        "Command failed: cd /Users/gene/Downloads/scancode-toolkit-2.2.1 && ./scancode --copyright --license --info --diag --only-findings  --strip-root --quiet --timeout 300 -n 3 -f json-pp /tmp/cd-7RHLrC/react /tmp/cd-Razsss\n"
    }
```

**Comment by geneh** [comment]
Resolved by https://github.com/Microsoft/ghcrawler/pull/123

ScanCode error is a separate problem that happens to huge repos (over ~150 MB). It should be resolved in the future by factoring scancode tool out of this app into a build process or something along those lines.
